-- Create a table for storing intern resumes
create table if not exists resumes (
  id bigint generated by default as identity primary key,
  user_email text not null unique,
  full_name text,
  university text,
  major text,
  graduation_year text,
  cgpa text,
  skills text[], -- Array of strings
  experience text,
  portfolio_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Set up Row Level Security (RLS)
alter table resumes enable row level security;

-- Policy to allow users to view their own resume
create policy "Users can view their own resume"
  on resumes for select
  using ( auth.uid()::text = user_email ); -- Note: This assumes we are using email as ID or mapping it somehow. 
  -- Since we are using a mock auth that saves email in local storage but using supabase client for data, 
  -- and the insert uses user_email column, we should probably just allow public insert/select for this demo 
  -- OR rely on the client key if RLS is off.
  -- For a real app with Supabase Auth, we would use auth.uid().

-- For this specific project state where Auth is mocked but DB is real:
-- We might need to disable RLS or create a policy that allows access based on the email column matching the input.
-- However, since the client is initialized with the anon key, RLS will block it unless policies exist.
-- Let's create a policy that allows all operations for now to avoid permission issues in this hybrid state, 
-- or better, allow based on the email column if possible, but the anon key doesn't have the user's email in the context.

-- SIMPLIFIED POLICY FOR DEV (Allow all access with Anon Key)
create policy "Enable all access for all users"
on resumes for all
using (true)
with check (true);
