
const { Client } = require('pg');

const connectionString = "postgres://postgres.wanxlxbaaqfukbxicpjk:KuxIbMkCRqQEp7ZA@aws-1-us-east-1.pooler.supabase.com:6543/postgres?supa=base-pooler.x";

const client = new Client({
    connectionString,
    ssl: {
        rejectUnauthorized: false
    }
});

const createApplicationsTableQuery = `
  CREATE TABLE IF NOT EXISTS applications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id BIGINT REFERENCES jobs(id),
    user_email TEXT NOT NULL,
    status TEXT DEFAULT 'Applied',
    applied_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
  );
`;

async function setupApplicationsTable() {
    try {
        await client.connect();
        console.log('Connected to database...');

        console.log('Creating "applications" table...');
        await client.query(createApplicationsTableQuery);
        console.log('Table "applications" created successfully.');

    } catch (err) {
        console.error('Error setting up applications table:', err);
    } finally {
        await client.end();
    }
}

setupApplicationsTable();
