
const { Client } = require('pg');

const connectionString = "postgres://postgres.wanxlxbaaqfukbxicpjk:KuxIbMkCRqQEp7ZA@aws-1-us-east-1.pooler.supabase.com:6543/postgres?sslmode=require&supa=base-pooler.x";

const client = new Client({
    connectionString,
    ssl: {
        rejectUnauthorized: false
    }
});

const createTableQuery = `
  CREATE TABLE IF NOT EXISTS jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    company TEXT NOT NULL,
    location TEXT NOT NULL,
    allowance TEXT,
    tags TEXT[],
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
  );
`;

const seedDataQuery = `
  INSERT INTO jobs (title, company, location, allowance, tags)
  VALUES 
    ('Software Engineering Intern', 'Grab Malaysia', 'Petaling Jaya, Selangor', '1,000 - 1,500', ARRAY['React', 'Node.js', 'Tech']),
    ('Digital Marketing Intern', 'AirAsia', 'Sepang, Selangor', '800 - 1,200', ARRAY['Marketing', 'Social Media', 'Travel']),
    ('Data Analyst Intern', 'Maybank', 'Kuala Lumpur', '1,200', ARRAY['SQL', 'Python', 'Finance']),
    ('Process Engineering Intern', 'Petronas', 'KLCC, Kuala Lumpur', '1,500', ARRAY['Engineering', 'Oil & Gas']),
    ('UI/UX Design Intern', 'Shopee Malaysia', 'Mid Valley, KL', '1,000', ARRAY['Figma', 'Design', 'E-commerce']),
    ('Finance Intern', 'CIMB Bank', 'Kuala Lumpur', '1,000', ARRAY['Accounting', 'Finance', 'Banking'])
  ON CONFLICT DO NOTHING;
`;

async function setupDatabase() {
    try {
        await client.connect();
        console.log('Connected to database...');

        console.log('Creating "jobs" table...');
        await client.query(createTableQuery);
        console.log('Table created successfully.');

        console.log('Seeding data...');
        await client.query(seedDataQuery);
        console.log('Data seeded successfully.');

    } catch (err) {
        console.error('Error setting up database:', err);
    } finally {
        await client.end();
    }
}

setupDatabase();
